name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / semgrep (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          semgrep_config: ./testdata/.semgrep.yml

  test-check-policy:
    name: runner / semgrep (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          semgrep_config: p/gosec

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / semgrep (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          semgrep_config: ./testdata/.semgrep.yml
          semgrep_target: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / semgrep (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          semgrep_config: ./testdata/.semgrep.yml
          reviewdog_flags: -filter-mode=file -fail-on-error
